version: "3.0"
services:
  main:
    build: ./main
    command: sleep infinity
    cap_add:
      - SYS_ADMIN
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ../:/data
      - ../configs:/configs
      - /tmp/restic-cache:/restic-cache
