version: '3.0'
services:
  main:
    build: ./main
    command: sleep infinity
    volumes:
      - ..:/data
  vite:
    build: ./vite
    container_name: vite-watch
    command: npm run watch
    volumes:
      - ../src/ui:/src
    restart: unless-stopped
    ports:
      - 5173:5173
