version: "3.0"
services:
  main:
    build: ./main
    command: sleep infinity
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ../:/data
      - ../configs:/configs
      - /tmp/restic-cache:/cache
