version: '3.0'
services:
  main:
    build: ./main
    command: sleep infinity
    volumes:
      - ..:/data
  go:
    build: ./go
    container_name: gow
    volumes:
      - ../src/restic-restore:/src/
      - ../configs:/configs
      - /tmp:/tmp
    working_dir: /src
    restart: unless-stopped
    ports:
      - 8888:8888
  vite:
    build: ./vite
    container_name: vite-watch
    command: npm run watch
    volumes:
      - ../src/ui:/src
    restart: unless-stopped
    ports:
      - 5173:5173
