version: "3.0"
services:
  main:
    build: ./main
    command: sleep infinity
    cap_add:
      # this is required to allow mount/unmount of file systems.
      - SYS_ADMIN
    security_opt:
      # this is required to allow access to the /dev/fuse device (though, SYS_ADMIN *should* be enough).
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ../:/data
      - ../configs:/configs
      - /tmp/restic-cache:/restic-cache
