name: Publish Docker image

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  push_to_registries:
    name: Push Docker image to hub.
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push (dev)
        uses: docker/build-push-action@v4
        if: ${{github.ref_type}} == 'branch' && ${{ github.ref_name }} == 'master'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restic-restore:dev
      - name: Build and push
        uses: docker/build-push-action@v4
        if: ${{github.ref_type}} == 'tag'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restic-restore:latest,${{ secrets.DOCKERHUB_USERNAME }}/restic-restore:${{ github.ref_name }}
